/* Autogenerated by /usr/bin/halcompile on Fri Aug 21 11:11:13 2026 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:pktuart_echo_diag:One-shot Mesa PktUART self-echo and reply diagnostic");
MODULE_INFO(linuxcnc, "pin:trigger:bit:0:in:Rising edge starts exactly one diagnostic request:false:None");
MODULE_INFO(linuxcnc, "pin:send_request:bit:0:in:True sends the one read request; false performs a passive idle-line capture:true:None");
MODULE_INFO(linuxcnc, "pin:done:bit:0:out:Set after all captured frames have been reported:false:None");
MODULE_INFO(linuxcnc, "pin:result:s32:0:out:0 waiting, 1 capture complete, negative on setup/send failure:0:None");
MODULE_INFO(linuxcnc, "pin:state:u32:0:out:Internal diagnostic state:0:None");
MODULE_INFO(linuxcnc, "pin:rx_status:u32:0:out:Raw PktUART RX status:0:None");
MODULE_INFO(linuxcnc, "pin:tx_status:u32:0:out:Raw PktUART TX status:0:None");
MODULE_INFO(linuxcnc, "pin:frame_count:u32:0:out:Number of received frames reported by PktUART:0:None");
MODULE_INFO(linuxcnc, "funct:_:1:");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_INFO(linuxcnc, "author:OpenAI Codex");
MODULE_INFO(linuxcnc, "descr:Clears PktUART, disables only receive-during-transmit masking, and logs either a passive idle capture or one Modbus function 04 request plus replies.");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *trigger;
    hal_bit_t *send_request;
    hal_bit_t *done;
    hal_s32_t *result;
    hal_u32_t *state;
    hal_u32_t *rx_status;
    hal_u32_t *tx_status;
    hal_u32_t *frame_count;
};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_bit_newf(HAL_IN, &(inst->trigger), comp_id,
        "%s.trigger", prefix);
    if(r != 0) return r;
    *(inst->trigger) = false;
    r = hal_pin_bit_newf(HAL_IN, &(inst->send_request), comp_id,
        "%s.send-request", prefix);
    if(r != 0) return r;
    *(inst->send_request) = true;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->done), comp_id,
        "%s.done", prefix);
    if(r != 0) return r;
    *(inst->done) = false;
    r = hal_pin_s32_newf(HAL_OUT, &(inst->result), comp_id,
        "%s.result", prefix);
    if(r != 0) return r;
    *(inst->result) = 0;
    r = hal_pin_u32_newf(HAL_OUT, &(inst->state), comp_id,
        "%s.state", prefix);
    if(r != 0) return r;
    *(inst->state) = 0;
    r = hal_pin_u32_newf(HAL_OUT, &(inst->rx_status), comp_id,
        "%s.rx-status", prefix);
    if(r != 0) return r;
    *(inst->rx_status) = 0;
    r = hal_pin_u32_newf(HAL_OUT, &(inst->tx_status), comp_id,
        "%s.tx-status", prefix);
    if(r != 0) return r;
    *(inst->tx_status) = 0;
    r = hal_pin_u32_newf(HAL_OUT, &(inst->frame_count), comp_id,
        "%s.frame-count", prefix);
    if(r != 0) return r;
    *(inst->frame_count) = 0;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
int rtapi_app_main(void) {
    int r = 0;
    comp_id = hal_init("pktuart_echo_diag");
    if(comp_id < 0) return comp_id;
    r = export("pktuart-echo-diag", 0);
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef trigger
#define trigger (0+*__comp_inst->trigger)
#undef send_request
#define send_request (0+*__comp_inst->send_request)
#undef done
#define done (*__comp_inst->done)
#undef result
#define result (*__comp_inst->result)
#undef state
#define state (*__comp_inst->state)
#undef rx_status
#define rx_status (*__comp_inst->rx_status)
#undef tx_status
#define tx_status (*__comp_inst->tx_status)
#undef frame_count
#define frame_count (*__comp_inst->frame_count)


#line 20 "diagnostics/pktuart/pktuart_echo_diag.comp"

#include "rtapi.h"
#include "hostmot2-serial.h"
#include <string.h>

#define PORT_NAME "hm2_7i95.0.pktuart.0"
#define WAIT_AFTER_SEND_CYCLES 150
#define MAX_CAPTURE_FRAMES 16
#define MAX_CAPTURE_BYTES 64

static const rtapi_u8 request[8] = {
    0x01, 0x04, 0x00, 0x00, 0x00, 0x01, 0x31, 0xCA
};

static int stage;
static int cycles;
static int current_frame;
static int pending_bytes;
static int trigger_seen;
static rtapi_u32 sizes[MAX_CAPTURE_FRAMES];
static rtapi_u32 rx_words[(MAX_CAPTURE_BYTES + 3) / 4];

static void print_frame(int index, int bytes, rtapi_u32 raw_size)
{
    int i;

    rtapi_print_msg(RTAPI_MSG_ERR,
        "PKTUART_CAPTURE frame=%d size_word=0x%08X bytes=%d data=",
        index, raw_size, bytes);
    for (i = 0; i < bytes; i++) {
        rtapi_u8 value = (rx_words[i / 4] >> ((i % 4) * 8)) & 0xFF;
        rtapi_print_msg(RTAPI_MSG_ERR, "%02X%s", value,
                        i + 1 == bytes ? "" : " ");
    }
    rtapi_print_msg(RTAPI_MSG_ERR, "\n");
}

FUNCTION(_)
{
    rtapi_u8 frames;
    rtapi_u16 request_size;
    int retval;
    int count;
    hm2_pktuart_config_t rx_config;
    hm2_pktuart_config_t tx_config;

    rx_status = hm2_pktuart_get_rx_status(PORT_NAME);
    tx_status = hm2_pktuart_get_tx_status(PORT_NAME);
    state = stage;

    if (!trigger) {
        trigger_seen = 0;
    }

    switch (stage) {
    case 0:
        if (!trigger || trigger_seen) {
            break;
        }
        trigger_seen = 1;
        done = 0;
        result = 0;
        frame_count = 0;
        cycles = 0;
        current_frame = 0;
        pending_bytes = 0;
        memset(sizes, 0, sizeof(sizes));
        memset(rx_words, 0, sizeof(rx_words));

        hm2_pktuart_reset(PORT_NAME);

        memset(&rx_config, 0, sizeof(rx_config));
        rx_config.baudrate = 19200;
        rx_config.filterrate = 38400;
        rx_config.ifdelay = 15;
        rx_config.flags = HM2_PKTUART_CONFIG_RXEN
                        | HM2_PKTUART_CONFIG_FLUSH
                        | HM2_PKTUART_CONFIG_FORCECONFIG;

        memset(&tx_config, 0, sizeof(tx_config));
        tx_config.baudrate = 19200;
        tx_config.drivedelay = 0;
        tx_config.ifdelay = 20;
        tx_config.flags = HM2_PKTUART_CONFIG_DRIVEEN
                        | HM2_PKTUART_CONFIG_DRIVEAUTO
                        | HM2_PKTUART_CONFIG_FLUSH
                        | HM2_PKTUART_CONFIG_FORCECONFIG;

        retval = hm2_pktuart_config(PORT_NAME, &rx_config, &tx_config, 0);
        if (retval < 0) {
            rtapi_print_msg(RTAPI_MSG_ERR,
                "PKTUART_CAPTURE setup_failed=%d\n", retval);
            result = retval;
            done = 1;
            stage = 7;
            break;
        }

        rtapi_print_msg(RTAPI_MSG_ERR,
            "PKTUART_CAPTURE configured port=%s version=%d baud=19200 framing=8N1 rx_mask=off request=01 04 00 00 00 01 31 CA\n",
            PORT_NAME, hm2_pktuart_get_version(PORT_NAME));
        stage = 1;
        break;

    case 1:
        if (++cycles < 5) {
            break;
        }
        if (!send_request) {
            rtapi_print_msg(RTAPI_MSG_ERR,
                "PKTUART_CAPTURE passive_listen_only transmitted_bytes=0\n");
            cycles = 0;
            stage = 2;
            break;
        }
        frames = 1;
        request_size = sizeof(request);
        retval = hm2_pktuart_send(PORT_NAME, request, &frames, &request_size);
        if (retval < 0) {
            rtapi_print_msg(RTAPI_MSG_ERR,
                "PKTUART_CAPTURE send_failed=%d\n", retval);
            result = retval;
            done = 1;
            stage = 7;
            break;
        }
        rtapi_print_msg(RTAPI_MSG_ERR,
            "PKTUART_CAPTURE sent_once bytes=8 request=01 04 00 00 00 01 31 CA\n");
        cycles = 0;
        stage = 2;
        break;

    case 2:
        if (++cycles < WAIT_AFTER_SEND_CYCLES) {
            break;
        }
        frame_count = (rx_status >> 16) & 0x1F;
        rtapi_print_msg(RTAPI_MSG_ERR,
            "PKTUART_CAPTURE collection_end rx_status=0x%08X tx_status=0x%08X frames=%u\n",
            rx_status, tx_status, frame_count);
        if (frame_count == 0) {
            if (rx_status & (HM2_PKTUART_RXMODE_ERRORPARITY
                           | HM2_PKTUART_RXMODE_ERRORRCFIFO
                           | HM2_PKTUART_RXMODE_ERROROVERRUN
                           | HM2_PKTUART_RXMODE_ERRORSTARTBIT)) {
                result = -2;
                rtapi_print_msg(RTAPI_MSG_ERR,
                    "PKTUART_CAPTURE no_complete_frames receiver_error_bits=0x%02X\n",
                    rx_status & 0x33);
            } else {
                result = 1;
                rtapi_print_msg(RTAPI_MSG_ERR,
                    "PKTUART_CAPTURE no_complete_frames receiver_error_bits=0x00\n");
            }
            done = 1;
            stage = 7;
            break;
        }
        memset(sizes, 0, sizeof(sizes));
        retval = hm2_pktuart_queue_get_frame_sizes(PORT_NAME, sizes);
        if (retval < 0) {
            rtapi_print_msg(RTAPI_MSG_ERR,
                "PKTUART_CAPTURE frame_size_read_failed=%d\n", retval);
            result = retval;
            done = 1;
            stage = 7;
            break;
        }
        stage = 3;
        break;

    case 3:
        rtapi_print_msg(RTAPI_MSG_ERR,
            "PKTUART_CAPTURE sizes=0x%08X 0x%08X 0x%08X 0x%08X\n",
            sizes[0], sizes[1], sizes[2], sizes[3]);
        current_frame = 0;
        stage = 4;
        break;

    case 4:
        if (current_frame >= MAX_CAPTURE_FRAMES || sizes[current_frame] == 0) {
            result = 1;
            done = 1;
            stage = 7;
            rtapi_print_msg(RTAPI_MSG_ERR,
                "PKTUART_CAPTURE complete frames=%u final_rx_status=0x%08X\n",
                frame_count, rx_status);
            break;
        }

        count = sizes[current_frame] & 0x3FF;
        if (count > MAX_CAPTURE_BYTES) {
            count = MAX_CAPTURE_BYTES;
        }
        pending_bytes = count;
        memset(rx_words, 0, sizeof(rx_words));
        retval = hm2_pktuart_queue_read_data(PORT_NAME, rx_words, count);
        if (retval < 0) {
            rtapi_print_msg(RTAPI_MSG_ERR,
                "PKTUART_CAPTURE frame_data_read_failed frame=%d error=%d\n",
                current_frame, retval);
            result = retval;
            done = 1;
            stage = 7;
            break;
        }
        stage = 5;
        break;

    case 5:
        print_frame(current_frame, pending_bytes, sizes[current_frame]);
        current_frame++;
        stage = 4;
        break;

    case 7:
        break;

    default:
        result = -99;
        done = 1;
        stage = 7;
        break;
    }
}

static int __comp_get_data_size(void) { return 0; }
